"""Build the upload set for Editorial Manager, self-contained and checked.

IPL takes one attempt: rejections are final and resubmission is not allowed, so the
package that goes into the form must be the right files, compiling on their side,
with nothing left to fill in.  This script assembles them from the single source:

  * note-ipl-submission.tex -- the elsarticle manuscript with the two shared text
    files inlined, so it compiles on its own wherever it is unpacked;
  * its PDF, its refs.bib and its .bbl (some forms want source, some want only the
    PDF; both are in the zip);
  * cover_letter.txt -- the letter, plain text, ready to paste, with the referee
    table removed (that belongs in the form);
  * referees.txt, highlights.txt, competing_interest.txt -- the three things the
    form asks for separately;
  * MANIFEST.txt -- which file goes where in the form.

The postal address is the one thing the repository cannot know.  Pass it and the
package is final; leave it out and the zip is named DRAFT and says why, rather
than quietly shipping a manuscript with a placeholder on its title page.

    python3 scripts/w_package.py \\
        --addressline "..." --city "..." --postcode "..." --country "..."
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IPL = os.path.join(ROOT, "submission", "ipl")
OUT = os.path.join(IPL, "package")
PLACEHOLDER = "FILL IN"


def md5(p):
    h = hashlib.md5()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 16), b""):
            h.update(b)
    return h.hexdigest()


def flatten(address):
    """The front matter as it stands, with street-level address fields added if given.

    The affiliation itself (organization and country) lives in ipl-body.tex, because it
    is the author's own standing affiliation and not a per-submission decision."""
    body = open(os.path.join(IPL, "ipl-body.tex"), encoding="utf-8").read()
    wrapper = open(os.path.join(IPL, "note_ipl.tex"), encoding="utf-8").read()
    cls = [l for l in wrapper.splitlines() if l.startswith("\\documentclass")][0]
    if address:
        extra = ", ".join("%s={%s}" % (k, v) for k, v in address.items())
        body = body.replace("\\affiliation{organization={Independent researcher}",
                            "\\affiliation{organization={Independent researcher}, " + extra)
    for name in ("note-abstract", "note-content"):
        text = open(os.path.join(ROOT, "note", name + ".tex"), encoding="utf-8").read()
        body = body.replace("\\input{../../note/%s}" % name,
                            "%% ---- %s.tex, inlined ----\n%s" % (name, text.rstrip()))
    body = body.replace("\\bibliography{refs}", "\\bibliography{refs}")
    head = ("%% Information Processing Letters -- submission manuscript.\n"
            "%% Generated by scripts/w_package.py from note/note-abstract.tex,\n"
            "%% note/note-content.tex and submission/ipl/ipl-body.tex.  Do not edit here:\n"
            "%% edit the sources and rebuild, or the copies drift apart.\n")
    return head + cls + "\n" + body


def latex(jobdir, job):
    env = dict(os.environ)
    for cmd in (["pdflatex", "-interaction=nonstopmode", job],
                ["bibtex", job],
                ["pdflatex", "-interaction=nonstopmode", job],
                ["pdflatex", "-interaction=nonstopmode", job]):
        subprocess.run(cmd, cwd=jobdir, env=env, capture_output=True, text=True)
    log = open(os.path.join(jobdir, job + ".log"), encoding="utf-8", errors="replace").read()
    pages = re.findall(r"\((\d+) pages", log)
    errors = [l for l in log.splitlines() if l.startswith("!")]
    return (int(pages[0]) if pages else 0), errors


def text_layer(pdf):
    """Does a copy-paste out of the PDF give words back, or mush?

    Publisher screening tools read the text layer, and a Type 1 font without a
    ToUnicode map turns 'five-dimensional' into 've-dimensional' and the en dash into
    a control character.  pypdf is not a dependency of this repository (the scripts run
    on a bare python3), so this check runs when pypdf happens to be importable and says
    so when it is not:

        python3 -m venv /tmp/pdfvenv && /tmp/pdfvenv/bin/pip install pypdf
        /tmp/pdfvenv/bin/python scripts/w_package.py
    """
    try:
        from pypdf import PdfReader
    except ImportError:
        return {"checked": False, "why": "pypdf not importable; run under a venv with pypdf"}
    txt = "\n".join(p.extract_text() or "" for p in PdfReader(pdf).pages)
    flat = re.sub(r"\s+", " ", txt)
    damage = sorted(set(re.findall(r"\b(?:ve-dimensional|nite|rst|eld|ned|gure|o er|di er)\b", flat)))
    want = ["five-dimensional", "finite", "confusability", "Polak\u2013Schrijver"]
    missing = [w for w in want if w not in flat]
    return {"checked": True, "chars": len(flat), "ligature_damage": damage,
            "words_missing": missing, "pass": not damage and not missing}


def plain(md_text, drop_from=None):
    t = md_text
    if drop_from and drop_from in t:
        t = t[:t.index(drop_from)].rstrip() + "\n"
    t = re.sub(r"\*\*(.+?)\*\*", r"\1", t, flags=re.S)
    t = re.sub(r"\*(.+?)\*", r"\1", t, flags=re.S)
    t = t.replace("`", "")
    return t


def main():
    ap = argparse.ArgumentParser()
    for f in ("addressline", "city", "postcode", "country"):
        ap.add_argument("--" + f, default=None)
    a = ap.parse_args()
    address = {k: v for k, v in vars(a).items() if v}
    shutil.rmtree(OUT, ignore_errors=True)
    os.makedirs(OUT)

    tex = flatten(address)
    # the flattened file must contain the shared text verbatim: a drift between the
    # submitted manuscript and the note the record carries would be the worst kind of bug
    for name in ("note-abstract", "note-content"):
        src = open(os.path.join(ROOT, "note", name + ".tex"), encoding="utf-8").read().rstrip()
        body = "\n".join(l for l in src.splitlines() if not l.startswith("%"))
        if body not in "\n".join(l for l in tex.splitlines() if not l.startswith("%")):
            sys.exit(f"the flattened manuscript does not contain {name}.tex verbatim")
    left = sorted(set(re.findall(r"FILL IN[^}]*", tex)))
    open(os.path.join(OUT, "note-ipl-submission.tex"), "w", encoding="utf-8").write(tex)
    shutil.copy(os.path.join(ROOT, "note", "refs.bib"), os.path.join(OUT, "refs.bib"))
    pages, errors = latex(OUT, "note-ipl-submission")

    # the pieces the form asks for separately
    letter = open(os.path.join(IPL, "cover_letter.md"), encoding="utf-8").read()
    open(os.path.join(OUT, "cover_letter.txt"), "w", encoding="utf-8").write(
        plain(letter, drop_from="---\n\n*Suggested referees"))
    refs_part = letter[letter.index("*Suggested referees"):] if "*Suggested referees" in letter else ""
    open(os.path.join(OUT, "referees.txt"), "w", encoding="utf-8").write(
        "Suggested referees, for the submission form (not for the letter).\n\n" + plain(refs_part))
    shutil.copy(os.path.join(IPL, "highlights.txt"), os.path.join(OUT, "highlights.txt"))
    # competing_interest.txt stays in submission/ipl/: it is a note to self, quoting the
    # guide, and the journal has no use for it. The declaration itself is in the
    # manuscript, and the .docx comes out of Elsevier's declarations tool inside the form.

    final = not left and pages and not errors
    manifest = f"""Information Processing Letters -- upload set
built by scripts/w_package.py; sources in note/ and submission/ipl/
checked against the Guide for Authors as read on 2026-09-26

  note-ipl-submission.pdf   the manuscript, as the review PDF.
  note-ipl-submission.tex   the same, LaTeX source, self-contained (elsarticle).
  refs.bib, *.bbl           its bibliography. REQUIRED, not optional: the guide says
                            editable source is required and "A PDF is not an
                            acceptable source file".
  cover_letter.txt          paste into the cover-letter box.
  referees.txt              the suggested referees, for the referee step.
  highlights.txt            REQUIRED: upload as a separate file (the guide asks for
                            3 to 5 bullets of at most 85 characters, in a file with
                            'highlights' in its name). Four bullets, 74-80 characters.
Competing interest: nothing to upload from here. In the form, open Elsevier's
declarations tool, select "I have nothing to declare", and upload the .docx it
produces at the 'attach/upload files' step. The declaration and the funding
sentence are already in the manuscript, before the references.


Data statement, when the form asks: the data and code are archived at
10.5281/zenodo.22979509, cited in the manuscript as a [dataset] reference, as this
journal's research-data Option C requires.

Text layer: checked -- a copy-paste out of the PDF returns 'five-dimensional',
'finite' and the en dash intact (cmap + T1 + Latin Modern in the preamble).

Manuscript: {pages} pages in the double-spaced review layout; five pages in the
journal's print layout, against its limit of nine. Abstract 162 words of 250,
six keywords of seven.

Affiliation on the title page: Independent researcher, Ukraine -- the author's own
standing line. Pass --addressline/--city/--postcode to this script if the form wants
street-level detail.

{'FINAL: no placeholder left.' if final else 'DRAFT: ' + ('; '.join(left) if left else 'the manuscript did not build')}
"""
    open(os.path.join(OUT, "MANIFEST.txt"), "w", encoding="utf-8").write(manifest)

    keep = ["note-ipl-submission.pdf", "note-ipl-submission.tex", "note-ipl-submission.bbl",
            "refs.bib", "cover_letter.txt", "referees.txt", "highlights.txt", "MANIFEST.txt"]
    name = ("ipl-submission.zip" if final else "ipl-submission-DRAFT-fill-the-address.zip")
    zpath = os.path.join(IPL, name)
    for stale in ("ipl-submission.zip", "ipl-submission-DRAFT-fill-the-address.zip"):
        if os.path.exists(os.path.join(IPL, stale)):
            os.remove(os.path.join(IPL, stale))
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in keep:
            p = os.path.join(OUT, f)
            if os.path.exists(p):
                z.write(p, f)
    # and it must come out the same length as the wrapper build of the same text
    wrapper_log = os.path.join(IPL, "note_ipl.log")
    wrapper_pages = 0
    if os.path.exists(wrapper_log):
        m = re.findall(r"\((\d+) pages", open(wrapper_log, encoding="utf-8",
                                               errors="replace").read())
        wrapper_pages = int(m[0]) if m else 0
    layer = text_layer(os.path.join(OUT, "note-ipl-submission.pdf"))
    rep = {
        "text_layer": layer,
        "wrapper_pages": wrapper_pages, "matches_wrapper": wrapper_pages == pages,
        "zip": os.path.relpath(zpath, ROOT), "zip_md5": md5(zpath),
        "final": bool(final), "placeholders_left": left,
        "review_pages": pages, "latex_errors": errors,
        "files": [{"name": f, "md5": md5(os.path.join(OUT, f)),
                   "bytes": os.path.getsize(os.path.join(OUT, f))}
                  for f in keep if os.path.exists(os.path.join(OUT, f))],
        "address_given": address,
    }
    with open(os.path.join(ROOT, "results", "json", "w_package.json"), "w") as f:
        json.dump(rep, f, indent=2)
    print(f"{os.path.relpath(zpath, ROOT)}  ({len(rep['files'])} files, {pages} pages, "
          f"{'FINAL' if final else 'DRAFT'})")
    if layer["checked"]:
        print(f"   text layer: {'PASS' if layer['pass'] else 'FAIL'} "
              f"(damage: {layer['ligature_damage'] or 'none'}, "
              f"missing: {layer['words_missing'] or 'none'})")
    else:
        print("   text layer: not checked --", layer["why"])
    for f in rep["files"]:
        print(f"   {f['name']:28} {f['bytes']:>8}  {f['md5'][:12]}")
    if left:
        print("   still to fill:", "; ".join(left))
        print("   rerun with: python3 scripts/w_package.py --addressline '...' --city '...' "
              "--postcode '...' --country '...'")
    return 0 if pages and not errors else 1


if __name__ == "__main__":
    sys.exit(main())
